package ast;

public interface Visitor<R> {
    R visitIntegerLiteral(IntegerLiteral expr);
    R visitFloatLiteral(FloatLiteral expr);
    R visitStringLiteral(StringLiteral expr);
    R visitBooleanLiteral(BooleanLiteral expr);
    R visitArrayLiteral(ArrayLiteral expr);
    R visitMapLiteral(MapLiteral expr);
    R visitNullLiteral(NullLiteral expr);
    R visitArrayIndex(ArrayIndex expr);
    R visitSetIndex(SetIndex expr);
    R visitCompoundSetExpr(CompoundSetExpr expr);
    R visitVariableExpr(VariableExpr expr);
    R visitAdd(Add expr);
    R visitSub(Sub expr);
    R visitMultiply(Multiply expr);
    R visitDivide(Divide expr);
    R visitModulo(Modulo expr);
    R visitNegative(Negative expr);
    R visitEquality(Equality expr);
    R visitInequality(Inequality expr);
    R visitGreater(Greater expr);
    R visitGreaterEqual(GreaterEqual expr);
    R visitLess(Less expr);
    R visitLessEqual(LessEqual expr);
    R visitAnd(And expr);
    R visitOr(Or expr);
    R visitNot(Not expr);
    R visitFunctionLiteralExpr(FunctionLiteralExpr expr);
    R visitCallExpr(CallExpr expr);
    R visitGetExpr(GetExpr expr);
    R visitSetExpr(SetExpr expr);
    R visitSuperExpr(SuperExpr expr);

    void visitBlockStmt(BlockStmt stmt);
    void visitWhileStmt(WhileStmt stmt);
    void visitForStmt(ForStmt stmt);
    void visitIfStmt(IfStmt stmt);
    void visitVariableDeclarationStmt(VariableDeclarationStmt stmt);
    void visitReturnStmt(ReturnStmt stmt);
    void visitBreakStmt(BreakStmt stmt);
    void visitContinueStmt(ContinueStmt stmt);
    void visitTryStmt(TryStmt stmt);
    void visitClassStmt(ClassStmt stmt);
    void visitEnumStmt(EnumStmt stmt);
    void visitExtendStmt(ExtendStmt stmt);
    void visitJavaBlockStmt(JavaBlockStmt stmt);
    void visitExpressionStmt(ExpressionStmt stmt);
    void visitSwitchStmt(SwitchStmt stmt);
}
